### ISSUE TITLE
Unclear usage instructions

### ISSUE THREAD

**Issue by kovetskiy** [ch3rn0v/dry#1]
What is `path_to_the_json_file`? How to obtain it?

As far as I understand I should somehow use semantic to obtain it, it would be great to have a full usage example (like I'm 5 years old) on any popular repository.

**Comment by ch3rn0v** [comment]
Hello and thanks a lot for the feedback!
I should definitely update README when I have time.

For now though, please take a look at [this part of semantic's documentation](https://github.com/github/semantic#parse).

In order to generate the json file, one needs to run semantic's parsing command with the `--json` option (in order to "Output JSON parse trees"):

`semantic parse --json [FILES...]`
